project_id = "eyntzaodrljvnzetvfdb"

[functions.robosttech-api]
verify_jwt = false

[functions.api-gateway]
verify_jwt = false

[functions.job-worker]
verify_jwt = false

[functions.health-check]
verify_jwt = false

[functions.smartapi-webhook]
verify_jwt = false
